[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning since NextAuth embeds NEXTAUTH_URL in build output
  SECRETS_SCAN_ENABLED = "false"

# Function configuration for better performance
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

# Increase timeout for serverless functions
[[functions]]
  path = "/api/*"
  included_files = ["src/**"]
  timeout = 30

# Headers for better performance
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables that should be set in Netlify dashboard
# MONGODB_URI - Your MongoDB connection string
# NEXTAUTH_SECRET - A random secret key for NextAuth
# NEXTAUTH_URL - Your production URL (e.g., https://your-app.netlify.app)
